### ISSUE TITLE
Add Support for SQLAlchemy 2.0

### ISSUE THREAD

**Issue by seano314** [rajivsarvepalli/mock-alchemy#303]
**Is your feature request related to a problem? Please describe.**
[SQLAlchemy 2.0](https://www.sqlalchemy.org/blog/2023/01/26/sqlalchemy-2.0.0-released/) was just released and `mock-alchemy` currently only supports SQLAlchemy 1.x.

**Describe the solution you'd like**
Add `mock-alchemy` support for SQLAlchemy 2.0

**Comment by seano314** [comment]
Note that mock-alchemy seems to run fine when run on SQLAlchemy 2.0. Given that mock-alchemy currently supports SQLAlchemy 1.4 and that the "[entire scope of 2.0’s new APIs and features are present and available within the 1.4 series](https://docs.sqlalchemy.org/en/14/changelog/migration_20.html#first-prerequisite-step-one-a-working-1-3-application)" this issue seems like it might be solved by just modifying the versioning within [noxfile.py](https://github.com/rajivsarvepalli/mock-alchemy/blob/master/noxfile.py#L13).

```
$ poetry lock
Because no versions of mock-alchemy match >0.2.5,<0.3.0
 and mock-alchemy (0.2.5) depends on SQLAlchemy (>=1.3.22,<2.0.0), mock-alchemy (>=0.2.5,<0.3.0) requires SQLAlchemy (>=1.3.22,<2.0.0).
So, because admin app backend depends on both SQLAlchemy (^2.0.0) and mock-alchemy (^0.2.5), version solving failed.
```

**Comment by jonyscathe** [comment]
Ideally, being able to mock 2.0 style ORM queries would also be good.
Code would be very similar to how query is currently handed, but with execute(), scalars() and scalar() rather than just query()
Though considering nothing has happened on this project for 15 or 16 months I don't think it is too likely that this will happen.

**Comment by GvandeSteeg** [comment]
Would be great if support for [`.where()`](https://stackoverflow.com/a/73160607) could be added too, I'm going to have to replace all my queries atm :sob:

**Comment by seano314** [comment]
Agree with both your thoughts. It looks like this package is basically dead --I submitted one PR but with no reply from the owner. 

With that being said, you probably don't want to use this within any type of production environment I've moved my system over to [create_mock_engine](https://docs.sqlalchemy.org/en/20/core/engines.html#sqlalchemy.create_mock_engine), which seems like it will be a better approach in the long run. 

I'm sure there is a better way to parse the SQL queries, but below is a short example of what I moved to if it's helpful to anyone.

```
async def mock_database(sql, *multiparams, **params):
    mock_return = mock.MagicMock()
    if 'WHERE' not in str(sql):
        mock_return.scalars.return_value = [_MOCK_CLASS_1, [_MOCK_CLASS_1]
        return mock_return
    if 'WHERE biomarker.id' in str(sql):
        mock_return.scalar.return_value = [_MOCK_CLASS_1
        return mock_return
    raise ValueError('Expressions not found in mock database: %s', sql)

engine = create_mock_engine("postgresql+asyncpg://", mock_database)

```

**Comment by rajivsarvepalli** [comment]
Added basic support for SQLAlchemy 2.0 using @seano314's CR as new version of mock-alchemy v0.2.6 (#328).

Sorry for the delayed responses here. If there are folks that are interested in contributing, feel free to open PRs. If anyone is interested in helping maintaining and feature development and wants to be added as collaborator, also feel free to reach out.
