### ISSUE TITLE
How does one work with abstract base models?

### ISSUE THREAD

**Issue by PeteW** [rajivsarvepalli/mock-alchemy#68]
Consider the following example where I have many models and I hoist the common fields into an abstract base.
```
from sqlalchemy.ext.declarative import declarative_base
Base = declarative_base()
class BaseModel(Base):
    __abstract__ = True  # this flag instructs sqlalchemy that BaseModel is not to be treated as a table
    created = Column(DateTime(), nullable=False, default=datetime.utcnow)
    createdby = Column(JSON(), nullable=False, default={})
    updated = Column(DateTime(), nullable=False, default=datetime.utcnow)
    updatedby = Column(JSON(), nullable=False, default={})
    disabled = Column(DateTime(), nullable=True)
    def __init__(self, *args, **kwargs):
        .... constructor things ...

class Concrete(BaseModel):
    __tablename__ = 'concrete'
    id = Column(BigInteger, primary_key=True)
    def __init__(self, *args, **kwargs):
        super(Concrete, self).__init__(args, kwargs)

session = UnifiedAlchemyMagicMock(data=[
    (
        [unittest.mock.call.query(Concrete)],
        [Concrete(id=1)]
    ),
]

session.query(Concrete).get(1)
-> None
```

When Concrete doesnt inherit from the abstract BaseModel, the mock returns a non-None object. I'm struggling to understand why this is. Can you share some insight?

**EDIT** it turns out the above case yields None when a constructor is defined for the abstract base. with no constructor it works as expected interesting enough.

**Comment by PeteW** [comment]
Additional bit of information/context: I generally agree with the philosophy behind mock-alchemy. But we often find ourselves with multiple tables having "common" fields such as created timestamps. And in that case it makes increasing sense to introduce a custom abstract base class to hold the common fields. And then it usually follows that we want the created time stamps to be set to datetime.utcnow for new records, and we usually do this using sqlalchemy events like before_insert, and we would define that event in the abstract base class once and expect it to apply to all concrete models. Of course these events dont actually execute in unit-testing if youre using mock-alchemy, which is understandable, so one conceivable workaround is to customize the constructors to pre-fill these fields. But doing that I've run into the issue above.

So, maybe my constructor-based workaround isnt the best approach I'm not sure. But if you were in a similar scenario I'd like to hear how you would approach it in a way that works with abstract base classes, events and mock-alchemy.

**Comment by rajivsarvepalli** [comment]
So actually as of now, `mock-alchemy` uses `getattr` to get attributes for retrieving with `get`. Perhaps this is not so intuitive, so I might look into getting values from SQLAlchemy objects using SQLAlchemy column attributes (or perhaps a combination of both). Sorry for the confusion, I should have made this clear in the documentation.

But, as for future changes, I think it makes more sense to grab the values from the SQLAlchemy Column attributes rather than Python object attributes. What do you think?


For the current situation, the change is not complex, but perhaps unintuitive.
```
class BaseModel(Base):
    __abstract__ = True  # this flag instructs sqlalchemy that BaseModel is not to be treated as a table
    created = Column(Integer, nullable=False, default=3)
    createdby = Column(Integer, nullable=False, default={})
    updated = Column(Integer, nullable=False, default=1)
    updatedby = Column(Integer, nullable=False, default={})
    disabled = Column(Integer, nullable=True)
    def __init__(self, *args, **kwargs):
        pass

class Concrete(BaseModel):
    __tablename__ = 'concrete'
    id = Column(Integer, primary_key=True)
    def __init__(self, id, *args, **kwargs):
        # the major change adding the primary key as an object attribute
        self.id = id
        super(Concrete, self).__init__(args, kwargs)
    def __eq__(self, other):
        return self.id == other.id
objs = Concrete(id=1)
session = UnifiedAlchemyMagicMock(data=[
        (
            [mock.call.query(Concrete)],
            [objs]
        ),
    ]
)
ret = session.query(Concrete).get(1)
assert ret == objs
```

For mocking purposes, I often use the Python object attributes, but I definitely see how this sort of redundant, and might look into  switching it to SQLAlchemy Column values.

**Comment by rajivsarvepalli** [comment]
Also, as a side note, I believe no constructor works because SQLAlchemy adds Columns as Python object attributes if no constructor is provided.

**Comment by PeteW** [comment]
To your point I'd love to get rid of the constructor. The thing is, without the constructors such as `created` which should have a default of `datetime.datetime.utcnow()` wont be assigned default values in the unit tests. 
As a matter of fact the constructors were introduced to ensure fields like `created` got their values and unit tests worked.
Its sort of a darned if you do, darned if you dont situation. But either way thanks for the insight.

**Comment by rajivsarvepalli** [comment]
Right, did you see the example above? The constructor is still present , you simply have to copy the primary key to the Python object attributes. That should work as well. I was merely giving an explanation for why I think no constructor works (not suggesting it is a good method of doing so).

**Comment by rajivsarvepalli** [comment]
I'm going to go ahead and close this issue since in (#84) I have added [documentation](https://mock-alchemy.readthedocs.io/en/latest/user_guide/index.html#abstract-classes) that addresses the issues discussed here. If there is further interest in this issue feel free start a discussion thread. Or if you feel I have not fully addressed this issue, feel free to open a new issue or request this one to be reopened.
